import { config } from '@/app/_infrastructure/config'
import { Util } from '@/app/_infrastructure/util'
import Image from 'next/image'
import 'react-quill/dist/quill.snow.css' // import styles
import { PostAction } from '../blog/_infrastructure/post.action'

export const metadata = {
  title: `Single Post Page | ${config.app.name}`,
  description: 'Generated by create next app',
}

/* TODO:
 * [ ] Show trending posts
 */

type TProps = {
  params: { id: string }
}

const SinglePost: React.FC<TProps> = async (props) => {
  const { data } = await PostAction.read(props.params.id)

  metadata.title = `${data.title} | ${config.app.name}`

  return (
    <main>
      <section>
        <div className="container mx-auto px-5 md:px-0 w-full md:w-10/12 lg:w-5/12 font-work">
          <div className="py-5">
            <h3 className="text-base-content font-semibold text-xl md:text-2xl lg:text-4xl leading-5 md:leading-10 ">
              {data.title}
            </h3>
            <div className="mt-3 md:mt-6 flex items-center gap-5 text-base-content/60">
              <div className=" flex items-center gap-3">
                <div className="avatar">
                  <div className="w-9 rounded-full">
                    <Image
                      src="https://lh3.googleusercontent.com/u/0/drive-viewer/AEYmBYSK636kqUCH7pz_I_IjoY9SlMOXkazNR_2_8cTeL0nQJgc5Fd-k7Duhdqx3Rf-avmGeivLfBhHU2n22P65vWM3yLi-i=w2880-h1412"
                      alt="avatar"
                      width={100}
                      height={100}
                    />
                  </div>
                </div>
                <a
                  href="/"
                  className=" text-xs md:text-sm font-medium hover:text-primary transition hover:duration-300"
                >
                  Framesta Fernando Wijaya
                </a>
              </div>
              <p className="text-xs md:text-sm">
                {Util.formatDate(data.createdAt)}
              </p>
            </div>
          </div>
          <div className="mt-8">
            <Image
              width="800"
              height="462"
              alt={'blog_image'}
              className={'rounded-xl'}
              src={data.imageUrl}
            />
          </div>
          <div
            className="font-serif"
            dangerouslySetInnerHTML={{ __html: data.content }}
          />
        </div>
      </section>
    </main>
  )
}

export default SinglePost
