import AuthorInfo from '@/app/_components/organism/authorInfo/AuthorInfo'
import LatestPost from '@/app/_components/organism/latestPost/LatestPost'
import { config } from '@/app/_utils/config'

export const metadata = {
  title: `Author Page | ${config.app.name}`,
  description: 'Generated by create next app',
}

const Author = () => {
  return (
    <main>
      <section>
        <AuthorInfo />
      </section>

      <section>
        <LatestPost />
      </section>
    </main>
  )
}

export default Author
