import { config } from '@/app/_infrastructure/config'
import AuthorInfo from '@/components/organism/authorInfo/AuthorInfo'
import LatestPost from '@/components/organism/latestPost/LatestPost'
import { PostAction } from '../blog/_infrastructure/post.action'

export const metadata = {
  title: `Author Page | ${config.app.name}`,
  description: 'Generated by create next app',
}

const Author = async () => {
  const { data } = await PostAction.fetch()

  return (
    <main>
      <section>
        <AuthorInfo />
      </section>

      <section>
        <LatestPost data={data} />
      </section>
    </main>
  )
}

export default Author
