import { API } from '@/app/_infrastructure/api.service'
import { config } from '@/app/_infrastructure/config'
import { ApiRes } from '@/app/_infrastructure/interfaces/api.response'
import AuthorInfo from '@/components/organism/authorInfo/AuthorInfo'
import LatestPost from '@/components/organism/latestPost/LatestPost'
import { IPost } from '../blog/_infrastructure/post.interface'

export const metadata = {
  title: `Author Page | ${config.app.name}`,
  description: 'Generated by create next app',
}

const fetch = async (): Promise<ApiRes<IPost[]>> => await API.get('/posts/view')

const Author = async () => {
  const { data } = await fetch()

  return (
    <main>
      <section>
        <AuthorInfo />
      </section>

      <section>
        <LatestPost data={data} />
      </section>
    </main>
  )
}

export default Author
