import BannerCard from '@/app/_components/molecules/card/BannerCard'
import Advertisement from '@/app/_components/organism/advertisement/Advertisement'
import LatestPost from '@/app/_components/organism/latestPost/LatestPost'
import { config } from '@/app/_utils/config'

export const metadata = {
  title: `Home Page | ${config.app.name}`,
  description: 'Generated by create next app',
}

export default function Home() {
  return (
    <main className="container mx-auto">
      <section>
        <BannerCard />
      </section>

      <section className="pt-12">
        <Advertisement />
      </section>

      <section className="my-20">
        <LatestPost />
      </section>

      <section className="mb-24">
        <Advertisement />
      </section>
    </main>
  )
}
