import { config } from '@/app/_infrastructure/config'
import { IndexSortOderEnum } from '@/app/_infrastructure/interfaces/index.interface'
import Advertisement from '@/components/organism/advertisement/Advertisement'
import LatestPost from '@/components/organism/latestPost/LatestPost'
import { PostAction } from './_infrastructure/post.action'

export const metadata = {
  title: `Blog Page | ${config.app.name}`,
  description: 'Generated by create next app',
}

const BlogListing = async () => {
  const { data } = await PostAction.fetch({
    sortField: 'createdAt',
    sortOrder: IndexSortOderEnum.Desc,
  })

  return (
    <main>
      <div className="container mx-auto">
        <section>
          <LatestPost data={data} />
        </section>

        <section className="mb-24">
          <Advertisement />
        </section>
      </div>
    </main>
  )
}

export default BlogListing
